[build]
  base = "."
  command = "ng build --configuration production"
  publish = "dist/frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200